### ISSUE TITLE
Support for custom configuration that will persist after a plugin update

### ISSUE THREAD

**Issue by nicktrosnant** [u3a-siteworks-development/u3a-siteworks-configuration#19]
We have a requirement to be able to include some custom configuration for individual sites.  My proposal is to add the facility to include an optional additional configuration file as the last step in the configuration plugin.  Something along the lines ...

`if (file_exists(ABSPATH . 'siteworksconfig.php')) {
    include (ABSPATH . 'siteworksconfig.php');
}`

So any site-specific configuration required can be added there and will still be present after a plugin update.

The immediate requirement is to add some code to some sites to generate some site specific structured data to be included in the <head> section.

Any thoughts on this approach?

**Comment by mike99christie** [comment]
I haven't understood how this code is to be created or maintained, nor why it should exist inside the siteworks configuration plugin rather than in some site-specific plugin.
This backdoor approach to adding functionality used by some sites seems to set a dangerous precedent.
If it is indeed just data not code, then how will this data be accessed by the rest of the website?
Perhaps the underlying issue needs to be discussed.

**Comment by nicktrosnant** [comment]
This is the kind of thing that in the old days would have been added to functions.php, but we're aiming to avoid such use of the theme file.

For example, on the main u3asite instance we need to include the following code to generate appropriate structured data:

`/**
 * Add structured data section to <head>
 */
add_action( 'wp_head', function () {
    echo <<< END
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Organization",
    "url" : "https://u3asite.uk/",
    "sameAs": [
        "https://siteworks.u3a.org.uk/",
        "https://www.u3a.org.uk/"
      ],
    "logo": "https://u3asite.uk/u3a-logo-512x512.png",
    "description":  "The u3a provides the opportunity for those no longer in work to come together and learn for fun.",
    "name" : "u3a SiteWorks"
}
</script>
END;
} );
`

This code is specific to that one site, but other code may be required on other sites for site-specific purposes.  At the moment, wherever an update to the configuration plugin is deployed I have to manually update that site's plugin file.  I'm happy to consider other mechanisms which is why I floated the question, but I don't think this justifies adding a separate plugin.  It struck me that other u3as self-hosting the SiteWorks plugins might also appreciate an "official" mechanism to add specific customisation that is not going to be overwritten by a plugin update.

**Comment by nicktrosnant** [comment]
Agreed that such code is better placed in a separate plugin.
